steps:
  # Step 1: Install dependencies
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        npm ci
    dir: "."  # karena semua file ada di root (termasuk package.json & vite.config.js)

  # Step 2: Build project (Vite)
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    dir: "."

  # Step 3: Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "."  # pastikan app.yaml dan dist sudah ada di sini

options:
  logging: CLOUD_LOGGING_ONLY
